import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        <div className="h[50%] bg-purple-700">
          <h1>Simple Pricing for your business</h1>
          <h4>Plans that are carefully crafted to suit your business.</h4>
        </div>
        <div className="h-[50%]">
          <div className="">
            <div className="bg-purple-300 flex justify-center items-center">
              <h3>Premium PRO</h3>
              <span>$329</span>
              <h6>billed just once</h6>
              <button>Get Started</button>
            </div>
            <div className="">
              <h5>
                Access these features when you get this pricing package for your
                business.
              </h5>
              <div className="">
                <span>International calling and messaging API</span>
                <span>Additional phone numbers</span>
                <span>Automated messages via Zapier</span>
                <span>24/7 support and consulting</span>
              </div>
            </div>
          </div>
          <div className="">
            <span>30 dayes money back Gurantee</span>
            <span></span>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
